package org.cardanofoundation.signify.app.config;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.Module;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleModule;
import org.cardanofoundation.signify.generated.keria.aiding.KeyStateRecordKtDeserializer;
import org.cardanofoundation.signify.generated.keria.aiding.KeyStateRecordKtMixIn;
import org.cardanofoundation.signify.generated.keria.model.KeyStateRecordKt;
import org.openapitools.jackson.nullable.JsonNullableModule;

/**
 * Centralizes Jackson configuration for OpenAPI-generated models.
 */
public final class GeneratedModelConfig {
    private GeneratedModelConfig() {
    }

    public static ObjectMapper mapper() {
        ObjectMapper mapper = new ObjectMapper();
        configure(mapper);
        return mapper;
    }

    /**
     * Apply the generated-model settings to an existing mapper.
     */
    public static void configure(ObjectMapper mapper) {
        // Disable strict validation that would block sealed interface deserialization
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        mapper.configure(DeserializationFeature.FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY, false);
        mapper.configure(DeserializationFeature.FAIL_ON_INVALID_SUBTYPE, false);
        mapper.configure(MapperFeature.ALLOW_FINAL_FIELDS_AS_MUTATORS, true);
        // Disable default type information processing to prevent validation of empty property names
        mapper.configure(MapperFeature.DEFAULT_VIEW_INCLUSION, false);
        mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        
        // Register MixIns for polymorphic sealed interfaces BEFORE modules
        // This disables Jackson's automatic @JsonTypeInfo processing
        mapper.addMixIn(KeyStateRecordKt.class, KeyStateRecordKtMixIn.class);
        
        // Register custom modules BEFORE JsonNullableModule to ensure they take precedence
        mapper.registerModule(generatedModule());
        mapper.registerModule(new SimpleModule() {
            @Override
            public void setupModule(SetupContext context) {
                super.setupModule(context);
                context.addBeanDeserializerModifier(new SealedInterfaceModifier());
            }
        });
        mapper.registerModule(new JsonNullableModule());
    }

    private static Module generatedModule() {
        SimpleModule module = new SimpleModule("GeneratedModelModule");
        
        // Register auto-generated deserializers for polymorphic sealed interfaces
        // These are generated by the Gradle sealed-interfaces task during model generation
        module.addDeserializer(KeyStateRecordKt.class, new KeyStateRecordKtDeserializer());
        
        return module;
    }
}